### ISSUE TITLE
Implement Brigadier support (feature)

### ISSUE THREAD

**Issue by DoubleNico** [QuadraBoy/commander#1]
[Brigadier](https://github.com/Mojang/brigadier) is the command parser and dispatcher for the java edition, adding support for it will be huge because it's a very modern way of doing commands nowadays in minecraft.

**Comment by QuadraBoy** [comment]
Yes definitely! My main goal right now is to add Brigadier support but I don't have an estimate date on when Brigadier will be supported since I'm still learning more about Brigadier. It will take time but it is achievable.
